### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by captaindavepdx** [jvandenaardweg/linkedin-profile-scraper#1]
Hi @jvandenaardweg ,

Thank you for building and sharing this awesome resource! I've learned a lot just by reading through your code. For example, the way you bypass reCaptcha using the session cookie was so simple, effective, and helpful - compared to using 3rd party api to solve reCaptcha. 

Anyways, thanks again! =]

David

**Comment by jvandenaardweg** [comment]
Hey @captaindavepdx ! Thank you for your kind words. Let me know if I can help you with anything ✌️

**Comment by captaindavepdx** [comment]
So, I've been stuck trying to click on the main buttons sequentially for several hours now. All my functions fire at the same time. I've tried `waitForSelector`, but the profile elements that I want to wait for don't exist yet. I've tried to remove the `async/await` statements, but most Puppeteer functions are async in nature. I've tried `setTimeout`, but it didn't seem to make a difference.

Jfyi, I'm still new to JavaScript. So, apologies in advance in case I missed something obvious. =]

When you have a moment could you please take peak at the code?

[https://pastebin.com/NduE1rBk](https://pastebin.com/NduE1rBk)
