### ISSUE TITLE
After recent build wrong sessionCookieValue signing in linkedin successfully

### ISSUE THREAD

**Issue by rehan-boon** [jvandenaardweg/linkedin-profile-scraper#12]
I entered the correct li_at cookie value for the sessionCookieValue and it didn't login linkedin and give me this error https://screencast.com/t/eC3alM9K9Na

But when i entered 'abcxyz' for sessionCookieValue  when i see logs it successfully signed in linkedin but this is the wrong cookie.

**Comment by jvandenaardweg** [comment]
Thanks for creating this issue. It seems the login check is outdated. I've pushed a [change](https://github.com/jvandenaardweg/linkedin-profile-scraper/commit/ff2c493b5882e7de9e11674aab86a14a6de9063a) to fix that.

Install the update:
```
npm install linkedin-profile-scraper@2.1.3
```

And try again :)

If you are still getting `timeout` errors after that, you can try this undocumented option:

```javascript
const scraper = new LinkedInProfileScraper({
   sessionCookieValue: '', // Fill in with your cookie value
   timeout: 30000 // Let the scraper wait max 30 seconds for the pages to load 
})
```

I'll update the documentation somewhere in the next few days to document all the available options.

Let me know if this update fixed your problem

**Comment by rehan-boon** [comment]
Thanks. `npm install linkedin-profile-scraper@2.1.3` worked for me.
