### ISSUE TITLE
The sample code given isnt compiling, please check :)

### ISSUE THREAD

**Issue by CajetanRodrigues** [jvandenaardweg/linkedin-profile-scraper#14]
![failing](https://user-images.githubusercontent.com/37682760/83919771-f970ac80-a798-11ea-9fa1-4ac793b404ba.PNG)

**Comment by 1nF0rmed** [comment]
The code is in TypeScript. Please ensure you have the typescript runtime for NodeJs installed.

**Comment by jvandenaardweg** [comment]
Hmm, I thought the build process takes care of this. I'll investigate, thanks for reporting!

**Comment by jvandenaardweg** [comment]
I've tested it with JavaScript and TypeScript and I cannot seem to reproduce this error. What environment are you using? And are you sure you have run `npm install linkedin-profile-scraper` ?
